GET http://localhost:8081/api/posts/

###

DELETE http://localhost:8081/api/posts/4

###

POST http://localhost:8081/api/posts/
Content-Type: application/json

{
  "id": 0,
  "content": "OLD Post 3"
}
